alfa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.animal.urls', namespace='animal')),
    path('pessoa/', include('apps.pessoa.urls', namespace='pessoa'))
]

apps/animal/urls.py
from django.urls import path
from .views import (AnimalCreateView, home, about, 
                    AnimalListView, AnimalDetailView, 
                    AnimalUpdateView, AnimalUpdateDetailView, 
                    AnimalDeleteView, AnimalDeleteDetailView)

app_name = 'animal'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('novo/', AnimalCreateView.as_view(), name='novo'),
    path('lista/', AnimalListView.as_view(), name='lista'),
    path('detalhe/<int:pk>/', AnimalDetailView.as_view(), name='detalhe'),
    path('atualizar/<int:pk>/', AnimalUpdateView.as_view(), name='atualizar'),
    path('detalhe/atualizar/<int:pk>/', AnimalUpdateDetailView.as_view(), name='detalhe-atualizar'),
    path('eliminar/confirmar/<int:pk>/', AnimalDeleteView.as_view(), name='eliminar'),
    path('detalhe/eliminar/confirmar/<int:pk>/', AnimalDeleteDetailView.as_view(), name='detalhe-eliminar')
]

apps/pessoa/urls.py
from django.urls import path
from .views import (contacts, PessoaCreateView, 
                    PessoaListView, PessoaDetailView, 
                    PessoaUpdateView, PessoaUpdateDetailView,
                    PessoaDeleteView, PessoaDeleteDetailView)

app_name = 'pessoa'

urlpatterns = [
     path('', contacts, name='contacts'),
     path('novo/', PessoaCreateView.as_view(), name='novo'),
     path('lista/', PessoaListView.as_view(), name='lista'),
     path('detalhe/<int:pk>/', PessoaDetailView.as_view(), name='detalhe'),
     path('atualizar/<int:pk>/', PessoaUpdateView.as_view(), name='atualizar'),
     path('detalhe/atualizar/<int:pk>/', PessoaUpdateDetailView.as_view(), name='detalhe-atualizar'),
     path('confirmar/eliminar/<int:pk>/', PessoaDeleteView.as_view(), name='eliminar'),
     path('detalhe/confirmar/eliminar/<int:pk>/', PessoaDeleteDetailView.as_view(), name='detalhe-eliminar')

]
    

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

apps/animal/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
    nome = models.CharField(max_length=50)
    especie = models.CharField(max_length=30)
    idade = models.IntegerField()

    def __str__(self):
        return f'{self.especie}: {self.nome}'

apps/pessoa/models.py
from django.db import models

# Create your models here.
# Vamos começar por criar modelos:

class Pessoa(models.Model): # vao ter esta herança dentro do modelo
    nome = models.CharField(max_length=50) # extenção de 50 caracteres
    idade = models.IntegerField() # verbose_name="idade"
    nif = models.CharField(max_length=9)
    email = models.EmailField()

# vamos fazer uma função que herda desta classe
    def __str__(self):
        return f'Nome: {self.nome}'

apps/animal/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Animal

# Create your views here.
#apresentação de página estática

def home(request):
    return render(request, 'animal/home.html')

def about(request):
    return render(request, 'animal/about.html')

class AnimalCreateView(CreateView):
    model = Animal
    fields = '__all__'
    success_url = reverse_lazy('animal:lista')

class AnimalListView(ListView):
    model = Animal

class AnimalDetailView(DetailView):
    model = Animal

class AnimalUpdateView(UpdateView):
    model = Animal
    fields = ['nome', 'idade']
    template_name = 'animal/animal_update.html'
    success_url = reverse_lazy('animal:lista')

class AnimalUpdateDetailView(UpdateView):
    model = Animal
    fields = ['nome', 'idade']
    template_name = 'animal/animal_detail_update.html'
   
    def get_success_url(self):
        return reverse('animal:detalhe', kwargs={'pk': self.object.id})

class AnimalDeleteView(DeleteView):
    model = Animal
    success_url = reverse_lazy('animal:lista')

class AnimalDeleteDetailView(DeleteView):
    model = Animal
    template_name = 'animal/animal_detail_confirm_delete.html'
    success_url = reverse_lazy('animal:lista')

apps/pessoa/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Pessoa

# Create your views here.
#apresentação de página estática

def contacts(request):
    return render(request, 'pessoa/contacts.html')

class PessoaCreateView(CreateView):
    model = Pessoa
    fields = '__all__'
    success_url = reverse_lazy('pessoa:lista')

class PessoaListView(ListView):
    model = Pessoa

class PessoaDetailView(DetailView):
    model = Pessoa

class PessoaUpdateView(UpdateView):
    model = Pessoa
    fields = ['nome', 'idade', 'email']
    template_name = 'pessoa/pessoa_update.html'
    success_url = reverse_lazy('pessoa:lista')

class PessoaUpdateDetailView(UpdateView):
    model = Pessoa
    fields = ['nome', 'idade', 'email']
    template_name = 'pessoa/pessoa_detail_update.html'
    
    def get_success_url(self):
        return reverse('pessoa:detalhe-atualizar',kwargs={'pk': self.object.id})

class PessoaDeleteView(DeleteView):
    model = Pessoa
    success_url: reverse_lazy('pessoa:lista')

class PessoaDeleteDetailView(DeleteView):
    model = Pessoa
    template_name = 'pessoa/pessoa_detail_confirm_delete.html' 
    success_url = reverse_lazy('pessoa:lista')

apps/animal/templates/animal/about.html
{% extends "base.html" %}

{% block content %}
<p>Teste About</p>
{% endblock %}

apps/animal/templates/animal/animal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h3>Animal</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <p>Tem a certeza que pretende eliminar o {{ object.especie }} {{ object.nome }} </p>        
        {{ form }}
        <br>
        <button class="btn btn-outline-danger" type="submit">Sim</button>
        <a class= "btn btn-outline-primary" href="{% url 'animal:lista' %}">Não</a>

    </form>

</div>
{% endblock %}

apps/animal/templates/animal/animal_detail.html
{% extends "base.html" %}

{% block content %}

<div class="content-section">
    <div class="row">
        <div class="col-1">
            <h3>Animal</h3>
        </div>
        <div class="col-1">
        <a class= "btn btn-outline-primary" href="{% url 'animal:detalhe-atualizar' object.id %}"><i class="fa-solid fa-pencil"></i></a>
        </div>
        <div class="col-1">
            <a class= "btn btn-outline-danger" href="{% url 'animal:detalhe-eliminar' object.id %}"><i class="fa-solid fa-trash-can"></i></a>
        </div>
    </div>
    <hr>
    <div style="padding:15px">
        <p><b>Nome: </b>{{ object.nome }}</p>
        <p><b>Espécie: </b>{{ object.especie }}</p>
        <p><b>Idade: </b>{{ object.idade }}</p>
    </div>
    <a class= "btn btn-outline-danger" href="{% url 'animal:lista' %}">Voltar</a>
</div>

{% endblock %}

apps/animal/templates/animal/animal_detail_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h3>Animal</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <p>Tem a certeza que pretende eliminar o {{ object.especie }} {{ object.nome }} </p>        
        {{ form }}
        <br>
        <button class="btn btn-outline-danger" type="submit">Sim</button>
        <a class= "btn btn-outline-primary" href="{% url 'animal:detalhe' object.id %}">Não</a>

    </form>

</div>
{% endblock %}

apps/animal/templates/animal/animal_detail_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Animal</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class= "btn btn-outline-danger" href="{% url 'animal:detalhe' object.id %}">Voltar</a>

    </form>

</div>
{% endblock %}

apps/animal/templates/animal/animal_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Animal</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}
        <br>
        <button class="btn btn-outline-primary" type="submit">Criar</button>
        <a class= "btn btn-outline-danger" href="{% url 'animal:lista' %}">Voltar</a>

    </form>

</div>
{% endblock %}

apps/animal/templates/animal/animal_list.html
{% extends "base.html" %}

{% block content %}
<h3>Animal</h3>
<hr>
<a class="btn btn-outline-primary" href="{% url 'animal:novo' %}"><i class="fa-solid fa-plus"></i></a>

<table class="table">
    <tr>
        <th>Nome do Animal</th>
        <th>Espécie do Animal</th>
        <th>Idade do Animal</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
{% for object in object_list %}
<tr>
    <td>{{ object.nome }}</td>
    <td>{{ object.especie }}</td>
    <td>{{ object.idade }}</td>
    <td><a class="btn btn-outline-primary" href="{% url 'animal:detalhe' object.id %}"><i class="fa-solid fa-eye"></i></a></td>
    <td><a class="btn btn-outline-primary" href="{% url 'animal:atualizar' object.id %}"><i class="fa-solid fa-pencil"></i></a></td>
    <td><a class="btn btn-outline-danger" href="{% url 'animal:eliminar' object.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
</tr>
{% endfor %}
</table>
{% endblock %}

apps/animal/templates/animal/animal_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h3>Animal</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class= "btn btn-outline-danger" href="{% url 'animal:lista' %}">Voltar</a>

    </form>

</div>
{% endblock %}

apps/animal/templates/animal/home.html
{% extends "base.html" %}

{% block content %}
<p>Teste Home</p>
{% endblock %}

apps/pessoa/templates/pessoa/contacts.html
{% extends "base.html" %}

{% block content %}
<p>Pessoa_Contactos</p>
{% endblock %}

apps/pessoa/templates/pessoa/pessoa_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h3>Pessoas</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <p>Tem a certeza que pretende eliminar "{{ object.nome }}"</p>
        {{ form }}
        <br>
        <button class="btn btn-outline-danger" type="submit">Sim</button>
        <a class= "btn btn-outline-primary" href="{% url 'pessoa:lista' %}">Não</a>
    </form>

</div>
{% endblock %}

apps/pessoa/templates/pessoa/pessoa_detail.html
{% extends "base.html" %}

{% block content %}

<div class="content-section">
    <div class="row">
        <div class="col-1">
            <h3>Pessoas</h3>
        </div>
        <div class="col-1">
            <a class= "btn btn-outline-primary" href="{% url 'pessoa:detalhe-atualizar' object.id %}"><i class="fa-solid fa-pencil"></i></a>
        </div>
        <div class="col-1">
            <a class= "btn btn-outline-danger" href="{% url 'pessoa:detalhe-eliminar' object.id %}"><i class="fa-solid fa-trash-can"></i></a>
        </div>
    </div>
    <hr>
    <div style="padding:15px">
        <p><b>Nome: </b>{{ object.nome }}</p>
        <p><b>Idade: </b>{{ object.idade }}</p>
        <p><b>NIF: </b>{{ object.nif }}</p>
        <p><b>E-mail: </b>{{ object.email }}</p>
    </div>
    <a class= "btn btn-outline-danger" href="{% url 'pessoa:lista' %}">Voltar</a>
</div>

{% endblock %}

apps/pessoa/templates/pessoa/pessoa_detail_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h3>Pessoas</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <p>Tem a certeza que pretende eliminar "{{ object.nome }}"</p>
        {{ form }}
        <br>
        <button class="btn btn-outline-danger" type="submit">Sim</button>
        <a class= "btn btn-outline-primary" href="{% url 'pessoa:detalhe' object.id %}">Não</a>
    </form>

</div>
{% endblock %}

apps/pessoa/templates/pessoa/pessoa_detail_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Pessoas</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class= "btn btn-outline-danger" href="{% url 'pessoa:detalhe' object.id %}">Voltar</a>
    </form>

</div>
{% endblock %}

apps/pessoa/templates/pessoa/pessoa_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}
        <br>
        <button class="btn btn-outline-primary" type="submit">Criar</button>
        <a class= "btn btn-outline-danger" href="{% url 'pessoa:lista' %}">Voltar</a>
    </form>

</div>
{% endblock %}

apps/pessoa/templates/pessoa/pessoa_list.html
{% extends "base.html" %}

{% block content %}
<h3>Pessoas</h3>
<hr>
<a class="btn btn-outline-primary" href="{% url 'pessoa:novo' %}"><i class="fa-solid fa-plus"></i></a>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Idade</th>
        <th>NIF</th>
        <th>E-mail</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
{% for object in object_list %}
<tr>
    <td>{{ object.nome }}</td>
    <td>{{ object.idade }}</td>
    <td>{{ object.nif }}</td>
    <td>{{ object.email }}</td>
    <td><a class="btn btn-outline-primary" href="{% url 'pessoa:detalhe' object.id %}"><i class="fa-solid fa-eye"></i></a></td>
    <td><a class="btn btn-outline-primary" href="{% url 'pessoa:atualizar' object.id %}"><i class="fa-solid fa-pencil"></i></a></td>
    <td><a class="btn btn-outline-danger" href="{% url 'pessoa:eliminar' object.id %}"><i class="fa-solid fa-trash-can"></i></a></td>

</tr>
{% endfor %}
</table>
{% endblock %}

apps/pessoa/templates/pessoa/pessoa_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Pessoas</h3>
<hr>
<div class="content-section">
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}
        <br>
        <button class="btn btn-outline-primary" type="submit">Guardar</button>
        <a class= "btn btn-outline-danger" href="{% url 'pessoa:lista' %}">Voltar</a>
    </form>

</div>
{% endblock %}

templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" 
            integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
            <script src="https://kit.fontawesome.com/aafe181546.js" crossorigin="anonymous"></script>
        <style>

        </style>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Olga Nabais</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'animal:home' %}">Home_Animal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'animal:about' %}">About_Animal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'animal:lista' %}">Animais</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pessoa:lista' %}">Pessoas</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pessoa:contacts' %}">Pessoa_Contactos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled">Desativado</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <div style="padding-top:20px;" class=container>
            <p>Projeto a decorrer - Olga Nabais</p>

            {% block content %}{% endblock %}

          </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>